# Generated by Django 2.1.7 on 2020-02-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_auto_20200212_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task',
            field=models.CharField(default=False, max_length=300),
        ),
    ]
